org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_id=uikitmc
mod_group_id=dev.flomik.uikitmc
mod_version=0.0.0-SNAPSHOT
mod_name=UIKitMC
mod_description=Design screens and overlays visually with alignment, spacing, and layout tools, then export clean Java code for Forge mods.
mod_authors=Flomik
mod_license=MIT

curse_slug=_curseslug_
curse_id=0

minecraft_version=1.20.1
mc_version=1.20.1
neo_version=47.1.106
neo_version_range=[47.1,)
loader_version_range=[47,)
mapping_channel=official

flib_version=0.0.14
flib_file=5495793
patchouli_version=84
jei_version=15.3.0.4
curios_version=5.7.2
crafttweaker_version=14.0.38

systemProp.org.gradle.native=false
