modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="uikitmc"
version="${mod_version}"
displayName="UIKitMC"
displayURL="https://www.curseforge.com/minecraft/mc-mods/_curseslug_"
logoFile=""
credits="Thanks to forge fml mcp Mojang"
authors="${mod_authors}"
mixinConfigs = "uikitmc.mixins.json"

description='''
${mod_description}
'''
[[dependencies.${mod_id}]]
    modId="forge" 
    mandatory=true 
    versionRange="${neo_version_range}" 
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="flib"
    mandatory=true
    versionRange="[${flib_version},)"
    ordering="NONE"
    side="BOTH"
	
	